---
- name: Copy web.html
  hosts: awsnode1
  become: true
  tasks:
  - name: Create /var/www/html directory
    become: true
    file:
      path: /var/www/html
      state: directory
      mode: "u=rw,g=wx,o=rwx"
      recurse: yes
  - name: copy dev web.html
    become: true
    copy:
      src: "dev_web.html"
      dest: /var/www/html/index.html
      mode: "u=rw,g=wx,o=rwx"
