---
- name: Copy web.html
  hosts: awsnode1
  become: true
  tasks:
  - name: Create /var/www/html directory
    file:
      path: /var/www/html
      state: directory
  - name: copy web.html
    copy:
      src: "dev_web.html"
      dest: /var/www/html/index.html
